config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :lists do
  resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord

  has_many :tasks, dependent: :destroy
  belongs_to :user

  validates :name, presence: true,
  length: { minimum: 5 },
  format: { with: /\A[a-zA-Z0-9 ]+\z/,
  message: "Please, just letters and numbers are allowed"}

  def self.to_csv(fields = column_names)
     CSV.generate(headers: true) do |csv|
       csv << fields
       all.each do |list|
         csv << list.attributes.values_at(*fields)
       end
     end
   end


end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :description, presence: true, format: { with: /\A[a-zA-Z0-9 ]+\z/, message: "Please, just letters and numbers are allowed" }, length: { minimum: 5 }

  def self.to_csv(fields = column_names)
     CSV.generate(headers: true) do |csv|
       csv << fields
       all.each do |task|
         csv << task.attributes.values_at(*fields)
       end
     end
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :lists, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_devise_params, if: :devise_controller?

private
  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :description, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:name, :description, :email, :password, :password_confirmation, :current_password, :image)
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /lists
  # GET /lists.json
  def index
    SendPendingTasksJob.perform_later(current_user)

    @lists = current_user.lists.all
    respond_to do |format|
      format.html
      format.csv {send_data @lists.to_csv}
      format.pdf do
        render pdf: 'Lists',
               template: 'lists/listsreport',
               layout: 'layout'
      end
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    respond_to do |format|
      format.html
      format.csv {send_data @list.tasks.to_csv}
      format.pdf {render template: 'tasks/tasksreport', pdf: 'Tasks'}
    end
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.', class:"alert alert-success" }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :completed)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def edit
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.create(task_params)
    redirect_to list_path(@list)
  end

  def update
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    @task.update(task_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    @task.destroy
    redirect_to list_path(@list)
  end

  private
    def task_params
      params.require(:task).permit(:description, :completed)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice  then "alert alert-info"
      when :success then "alert alert-success"
      when :error   then "alert alert-error"
      when :alert   then "alert alert-error"
    end
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg|%>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <small><sup>x</sup></small>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">

  <div class="container">

    <div class="navbar-header">
      <%= link_to 'To-do', root_path, class:'nav-link' %>
    </div>

    <ul class="nav navbar-nav">
      <ul class="navbar-nav">
      <% if !current_user %>

        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, "data-no-turbolink":false %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, "data-no-turbolink":false %>
        </li>

      <% else %>
        <li>
          Welcome <%= current_user.name %>
        </li>
        <li>
          <% if current_user.image.attached? %>
          <%= image_tag(current_user.image)%>
          <% else %>

          <% end %>
        </li>

        <li>
          <%= link_to 'Edit Profile', edit_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, "data-no-turbolink":false %>
        </li>

      <% end %>
      </ul>
    </ul>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>V2Todo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <title>Demo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="container">

    <nav class="navbar navbar-expand-sm bg-light">
  <!-- Links -->

      <ul class="navbar-nav">
      <% if !current_user %>

        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
        </li>

      <% else %>

        <li class="nav-item">
          Welcome <%= current_user.name %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
        </li>

      <% end %>
      </ul>
    </nav>

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <%= value %>
        </div>
      <% end %>

<!--      <% if current_user %>
          Welcome <%= current_user.email %> | <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
          <%= link_to 'Login', new_user_session_path %>
      <% end %>
-->

      <%= yield %>
    <div>
  </body>
</html>

app/views/layouts/layout.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <title>V2Todo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <%= wicked_pdf_stylesheet_link_tag 'pdf' %>  

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:'form-control' %>
  </div>

  <div class="form-group form-check">
    <%= form.label :completed, class:"form-check-label"%>
    <%= form.check_box :completed, class:"form-control"%>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/lists/_row.html.erb
<td><%= @task.completed %></td>
<td><%= link_to 'Edit', edit_list_task_path(@list, task), class:"btn btn-success btn-block" %></td>
<td><%= link_to 'Delete', [task.list, task],
class:"btn btn-danger btn-block",
method: :delete,
data: { confirm: 'Are you sure?'}
%></td>

app/views/lists/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list.tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.completed %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lists/edit.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3 text-center">
    <div class="card">
      <div class="card-body">
        <h1>Edit List</h1>
        <%= render 'form', list: @list %>
        <%= link_to 'Show', @list %> |
        <%= link_to 'Back', lists_path %>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="jumbotron">
  <h1>
    Lists
    <%= link_to 'CSV', lists_path(format: 'csv'), class:'btn btn-info' %>
    <%= link_to 'PDF', lists_path(format: 'pdf'), class:'btn btn-info' %>
  </h1>
</div>


<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.completed %></td>
        <td><%= link_to 'Show', list, class:"btn btn-primary btn-block" %></td>
        <td><%= link_to 'Edit', edit_list_path(list),class:"btn btn-success btn-block" %></td>
        <td><%= link_to 'Destroy', list, method: :delete,
          class:"btn btn-danger btn-block",
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path, class:"btn btn-primary" %>

app/views/lists/listsreport.pdf.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.completed %></td>
        <td><%= link_to 'Show', list, class:"btn btn-primary btn-block" %></td>
        <td><%= link_to 'Edit', edit_list_path(list),class:"btn btn-success btn-block" %></td>
        <td><%= link_to 'Destroy', list, method: :delete,
          class:"btn btn-danger btn-block",
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lists/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3 text-center">
    <div class="card">
      <div class="card-body">
        <h1>New List</h1>
        <%= render 'form', list: @list %>
        <%= link_to 'Back', lists_path %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="jumbotron">
  <h1>
    <strong>List Name:</strong> <%= @list.name %>
    <%= link_to 'CSV', list_path(@list, format: 'csv'), class:'btn btn-info' %>
    <%= link_to 'PDF', list_path(@list, format: 'pdf'), class:'btn btn-info' %>
  </h1>


</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Task Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list.tasks.each do |task| %>
      <% if task.completed %>
          <tr class="table-secondary">
            <td class="striker"><%= task.description %></td>
            <td><%= task.completed %></td>
            <td><%= link_to 'Edit', edit_list_task_path(@list, task), class:"btn btn-success btn-block" %></td>
            <td><%= link_to 'Delete', [task.list, task],
            class:"btn btn-danger btn-block",
            method: :delete,
            data: { confirm: 'Are you sure?'}
            %></td>
          </tr>
      <% else %>
          <tr class="table-primary">
            <td><%= task.description %></td>
            <td><%= task.completed %></td>
            <td><%= link_to 'Edit', edit_list_task_path(@list, task), class:"btn btn-success btn-block" %></td>
            <td><%= link_to 'Delete', [task.list, task],
            class:"btn btn-danger btn-block",
            method: :delete,
            data: { confirm: 'Are you sure?'}
            %></td>
          </tr>

      <% end %>
    <% end %>
  </tbody>
</table>

  <div class="row">
    <div class="col-md-6 offset-md-3 text-center">
        <div class="card">
          <div class="card-body">
            <h2>Add a Task:</h2>
            <%= render 'tasks/form' %>
            <%= link_to 'Edit', edit_list_path(@list) %> |
            <%= link_to 'Back', lists_path %>
          </div>
        </div>
    </div>
  </div>

app/views/tasks/_form.html.erb
<%= form_with(model: [ @list, @list.tasks.build ], local: true) do |form| %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="form-group form-check">
    <%= form.label :completed, class:"form-check-label"%>
    <%= form.check_box :completed, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.submit 'Add Task', class:"btn btn-primary btn-block" %>
  </div>

<% end %>

app/views/tasks/_task.html.erb
<p>
  <strong>List Name:</strong>
  <%= @list.name %>
</p>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Task Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list.tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.completed %></td>
        <td><%= link_to 'Show', "#" %></td>
        <td><%= link_to 'Edit', "#" %></td>
        <td>  <%= link_to 'Delete', [task.list, task],
        method: :delete,
        data: { confirm: 'Are you sure?'}
        %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3 text-center">
    <div class="card">
      <div class="card-body">
          <h1>Edit Task <%= @task.description %></h1>
          <%= form_with(model:[@list, @list.tasks.find(@task.id)], local: true) do |form| %>
            <div class="form-group">
              <%= form.label :description %>
              <%= form.text_field :description, class:"form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :completed %>
              <%= form.check_box :completed, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= form.submit 'Edit Task', class: 'btn btn-primary btn-block' %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/tasks/tasksreport.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%# <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
<link rel="stylesheet" type="text/text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body class="main-content">

  <h1>List Name: <%= @list.name %></h1>
  <br>
  <div class="contentTable">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
        </tr>
      </thead>
      <tbody>
        <% @list.tasks.each do |task| %>
          <tr>
            <th scope="row"><%= task.description %></th>
            <td><%= task.completed %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class='jumbotron'>
  <h1> Welcome to TodoApp </h1>
  <h2>CRUD Lists and Tasks</h2>
  <p>
    <%= link_to 'View all Lists', lists_path, class:'btn btn-primary' %>
  </p>
</div>